export const tileNameObject = {
    "acaciaFence": "Acacia Fence",
    "acacia_fence_gate": "Acacia Fence Gate",
    "activator_rail": "Activator Rail",
    "allow": "Allow",
    "air": "Air",
    "unknown": "Unknown",
    "deny": "Deny",
    "border_block": "Border",
    "anvil": "Anvil",
    "barrier": "Barrier",
    "beacon": "Secondary Power",
    "beehive": "Beehive",
    "bee_nest": "Bee Nest",
    "target": "Target",
    "bed": "Bed is obstructed",
    "bedrock": "Bedrock",
    "bell": "Bell",
    "camera": "Camera",
    "conduit": "Conduit",
    "invisibleBedrock": "Invisible Bedrock",
    "beetroot": "Beetroot",
    "big_dripleaf": "Big Dripleaf",
    "small_dripleaf_block": "Small Dripleaf",
    "hanging_roots": "Hanging Roots",
    "dirt_with_roots": "Rooted Dirt",
    "spore_blossom": "Spore Blossom",
    "azalea_leaves": "Azalea Leaves",
    "azalea_leaves_flowered": "Flowered Azalea Leaves",
    "azalea": "Azalea",
    "flowering_azalea": "Flowering Azalea",
    "cave_vines": "Cave Vines",
    "cave_vines_body_with_berries": "Cave Vines",
    "cave_vines_head_with_berries": "Cave Vines",
    "glow_berries": "Glow Berries",
    "moss_block": "Moss Block",
    "moss_carpet": "Moss Carpet",
    "birchFence": "Birch Fence",
    "birch_fence_gate": "Birch Fence Gate",
    "blast_furnace": "Blast Furnace",
    "bone_block": "Bone Block",
    "coal_block": "Block of Coal",
    "diamond_block": "Block of Diamond",
    "emerald_block": "Block of Emerald",
    "gold_block": "Block of Gold",
    "iron_block": "Block of Iron",
    "lapis_block": "Lapis Lazuli Block",
    "redstone_block": "Block of Redstone",
    "bookshelf": "Bookshelf",
    "brick_block": "Brick Block",
    "brown_mushroom": "Brown Mushroom",
    "brown_mushroom_block": [
        "Mushroom",
        "Mushroom Stem",
        "Brown Mushroom Block"
    ],
    "wooden_button": "Oak Button",
    "acacia_button": "Acacia Button",
    "birch_button": "Birch Button",
    "dark_oak_button": "Dark Oak Button",
    "jungle_button": "Jungle Button",
    "respawn_anchor": "Your respawn anchor was out of charges, missing or obstructed",
    "spruce_button": "Spruce Button",
    "stone_button": "Stone Button",
    "cactus": "Cactus",
    "cake": "Cake",
    "dried_kelp_block": "Dried Kelp Block",
    "carrot": "Carrots",
    "carved_pumpkin": "Carved Pumpkin",
    "cauldron": "Cauldron",
    "chalkboard": [
        "Slate",
        "Poster",
        "Board"
    ],
    "chest": "Chest",
    "ender_chest": "Ender Chest",
    "jigsaw": "Jigsaw Block",
    "honey_block": "Honey Block",
    "honeycomb_block": "Honeycomb Block",
    "lodestone": "Lodestone",
    "nether_sprouts": "Nether Sprouts",
    "crimson_stem": "Crimson Stem",
    "warped_stem": "Warped Stem",
    "stripped_crimson_stem": "Stripped Crimson Stem",
    "stripped_warped_stem": "Stripped Warped Stem",
    "crimson_hyphae": "Crimson Hyphae",
    "warped_hyphae": "Warped Hyphae",
    "stripped_crimson_hyphae": "Stripped Crimson Hyphae",
    "stripped_warped_hyphae": "Stripped Warped Hyphae",
    "crimson_planks": "Crimson Planks",
    "warped_planks": "Warped Planks",
    "crimson_door": "Crimson Door",
    "warped_door": "Warped Door",
    "crimson_trapdoor": "Crimson Trapdoor",
    "warped_trapdoor": "Warped Trapdoor",
    "crimson_standing_sign": "Crimson Sign",
    "warped_standing_sign": "Warped Sign",
    "crimson_wall_sign": "Crimson Sign",
    "warped_wall_sign": "Warped Sign",
    "crimson_stairs": "Crimson Stairs",
    "warped_stairs": "Warped Stairs",
    "crimson_fence": "Crimson Fence",
    "warped_fence": "Warped Fence",
    "crimson_fence_gate": "Crimson Fence Gate",
    "warped_fence_gate": "Warped Fence Gate",
    "crimson_button": "Crimson Button",
    "warped_button": "Warped Button",
    "crimson_pressure_plate": "Crimson Pressure Plate",
    "warped_pressure_plate": "Warped Pressure Plate",
    "crimson_slab": "Crimson Slab",
    "warped_slab": "Warped Slab",
    "crimson_double_slab": "Crimson Slab",
    "warped_double_slab": "Warped Slab",
    "shroomlight": "Shroomlight",
    "crimson_nylium": "Crimson Nylium",
    "warped_nylium": "Warped Nylium",
    "basalt": "Basalt",
    "polished_basalt": "Polished Basalt",
    "blackstone": "Blackstone",
    "polished_blackstone_bricks": "Polished Blackstone Bricks",
    "cracked_polished_blackstone_bricks": "Cracked Polished Blackstone Bricks",
    "polished_blackstone_brick_stairs": "Polished Blackstone Brick Stairs",
    "blackstone_stairs": "Blackstone Stairs",
    "blackstone_wall": "Blackstone Wall",
    "polished_blackstone_brick_wall": "Polished Blackstone Brick Wall",
    "chiseled_polished_blackstone": "Chiseled Polished Blackstone",
    "gilded_blackstone": "Gilded Blackstone",
    "blackstone_slab": "Blackstone Slab",
    "polished_blackstone_brick_slab": "Polished Blackstone Brick Slab",
    "chain": "Chain",
    "soul_soil": "Soul Soil",
    "soul_fire": "Soul Fire",
    "polished_blackstone": "Polished Blackstone",
    "polished_blackstone_stairs": "Polished Blackstone Stairs",
    "polished_blackstone_slab": "Polished Blackstone Slab",
    "polished_blackstone_pressure_plate": "Polished Blackstone Pressure Plate",
    "polished_blackstone_button": "Polished Blackstone Button",
    "polished_blackstone_wall": "Polished Blackstone Wall",
    "soul_campfire": "Soul Campfire",
    "chiseled_nether_bricks": "Chiseled Nether Bricks",
    "cracked_nether_bricks": "Cracked Nether Bricks",
    "quartz_bricks": "Quartz Bricks",
    "trapped_chest": "Trapped Chest",
    "shulkerBoxWhite": "White Shulker Box",
    "shulkerBoxOrange": "Orange Shulker Box",
    "shulkerBoxMagenta": "Magenta Shulker Box",
    "shulkerBoxLightBlue": "Light Blue Shulker Box",
    "shulkerBoxYellow": "Yellow Shulker Box",
    "shulkerBoxLime": "Lime Shulker Box",
    "shulkerBoxPink": "Pink Shulker Box",
    "shulkerBoxGray": "Gray Shulker Box",
    "shulkerBoxSilver": "Light Gray Shulker Box",
    "shulkerBoxCyan": "Cyan Shulker Box",
    "shulkerBoxPurple": "Purple Shulker Box",
    "shulkerBoxBlue": "Blue Shulker Box",
    "shulkerBoxBrown": "Brown Shulker Box",
    "shulkerBoxGreen": "Green Shulker Box",
    "shulkerBoxRed": "Red Shulker Box",
    "shulkerBoxBlack": "Black Shulker Box",
    "shulkerBox": "Shulker Box",
    "chorus_flower": "Chorus Flower",
    "chorus_plant": "Chorus Plant",
    "stained_glass": [
        "White Stained Glass",
        "Light Gray Stained Glass",
        "Gray Stained Glass",
        "Black Stained Glass",
        "Brown Stained Glass",
        "Red Stained Glass",
        "Orange Stained Glass",
        "Yellow Stained Glass",
        "Lime Stained Glass",
        "Green Stained Glass",
        "Cyan Stained Glass",
        "Light Blue Stained Glass",
        "Blue Stained Glass",
        "Purple Stained Glass",
        "Magenta Stained Glass",
        "Pink Stained Glass"
    ],
    "stained_glass_pane": [
        "White Stained Glass Pane",
        "Light Gray Stained Glass Pane",
        "Gray Stained Glass Pane",
        "Black Stained Glass Pane",
        "Brown Stained Glass Pane",
        "Red Stained Glass Pane",
        "Orange Stained Glass Pane",
        "Yellow Stained Glass Pane",
        "Lime Stained Glass Pane",
        "Green Stained Glass Pane",
        "Cyan Stained Glass Pane",
        "Light Blue Stained Glass Pane",
        "Blue Stained Glass Pane",
        "Purple Stained Glass Pane",
        "Magenta Stained Glass Pane",
        "Pink Stained Glass Pane"
    ],
    "clay": "Clay Block",
    "hardened_clay": "Terracotta",
    "stained_hardened_clay": "Terracotta",
    "structure_block": "Structure Block",
    "structure_void": "Structure Void",
    "wool": "Wool",
    "cobblestone_wall": [
        "Mossy Cobblestone Wall",
        "Cobblestone Wall ",
        "Granite Wall",
        "Diorite Wall",
        "Andesite Wall",
        "Sandstone Wall",
        "Brick Wall",
        "Stone Brick Wall",
        "Mossy Stone Brick Wall",
        "Nether Brick Wall",
        "End Stone Brick Wall",
        "Prismarine Wall",
        "Red Sandstone Wall",
        "Red Nether Brick Wall"
    ],
    "cocoa": "Cocoa",
    "command_block": "Command Block",
    "composter": "Composter",
    "light_block": "Light Block",
    "repeating_command_block": "Repeating Command Block",
    "chain_command_block": "Chain Command Block",
    "wheat": "Crops",
    "darkOakFence": "Dark Oak Fence",
    "dark_oak_fence_gate": "Dark Oak Fence Gate",
    "daylight_detector": "Daylight Sensor",
    "deadbush": "Dead Bush",
    "detector_rail": "Detector Rail",
    "dirt": "Dirt",
    "podzol": "Podzol",
    "purpur_block": [
        "Purpur Block",
        "Purpur Pillar",
        "Chiseled Purpur"
    ],
    "dispenser": "Dispenser",
    "iron_door": "Iron Door",
    "doorWood": "Wooden Door",
    "double_plant": "Plant",
    "dragon_egg": "Dragon Egg",
    "dropper": "Dropper",
    "enchanting_table": "Enchantment Table",
    "enderChest": "Ender Chest",
    "end_portal_frame": "End Portal",
    "farmland": "Farmland",
    "fletching_table": "Fletching Table",
    "fence": "Oak Fence",
    "fence_gate": "Oak Fence Gate",
    "iron_bars": "Iron Bars",
    "fire": "Fire",
    "yellow_flower": "Flower",
    "crimson_roots": [
        "Crimson Roots"
    ],
    "warped_roots": [
        "Warped Roots"
    ],
    "red_flower": "Flower",
    "wither_rose": "Wither Rose",
    "furnace": "Furnace",
    "glass": "Glass",
    "golden_rail": "Powered Rail",
    "grass": "Grass Block",
    "grass_path": "Dirt Path",
    "gravel": "Gravel",
    "hay_block": "Hay Bale",
    "netherrack": "Netherrack",
    "soul_sand": "Soul Sand",
    "hopper": "Hopper",
    "ice": "Ice",
    "packed_ice": "Packed Ice",
    "blue_ice": "Blue Ice",
    "frosted_ice": "Frosted Ice",
    "iron_trapdoor": "Iron Trapdoor",
    "jukebox": "Jukebox",
    "jungleFence": "Jungle Fence",
    "jungle_fence_gate": "Jungle Fence Gate",
    "ladder": "Ladder",
    "flowing_lava": "Lava",
    "leaves": "Leaves",
    "leaves2": [
        "Acacia Leaves",
        "Dark Oak Leaves"
    ],
    "lever": "Lever",
    "glowstone": "Glowstone",
    "glow_lichen": "Glow Lichen",
    "lightning_rod": "Lightning Rod",
    "lit_pumpkin": "Jack o'Lantern",
    "lockedchest": "Locked chest",
    "log": "Log",
    "magma": "Magma Block",
    "melon_block": "Melon",
    "mob_spawner": "Monster Spawner",
    "monster_egg": "Infested Stone",
    "mushroom": "Mushroom",
    "noteblock": "Note Block",
    "mycelium": "Mycelium",
    "nether_brick": "Nether Brick Block",
    "red_nether_brick": "Red Nether Brick",
    "nether_brick_fence": "Nether Brick Fence",
    "quartz_ore": "Nether Quartz Ore",
    "netherreactor": "Not the correct pattern!",
    "nether_wart": "Nether Wart",
    "nether_wart_block": "Nether Wart Block",
    "warped_wart_block": "Warped Wart Block",
    "unlit_redstone_torch": "Redstone Torch",
    "redstone_torch": "Redstone Torch",
    "soul_torch": "Soul Torch",
    "obsidian": "Obsidian",
    "coal_ore": "Coal Ore",
    "diamond_ore": "Diamond Ore",
    "emerald_ore": "Emerald Ore",
    "gold_ore": "Gold Ore",
    "iron_ore": "Iron Ore",
    "copper_ore": "Copper Ore",
    "lapis_ore": "Lapis Lazuli Ore",
    "redstone_ore": "Redstone Ore",
    "oreRuby": "Ruby Ore",
    "observer": "Observer",
    "piston": "Piston",
    "sticky_piston": "Sticky Piston",
    "portal": "Portal",
    "potatoes": "Potatoes",
    "stone_pressure_plate": "Stone Pressure Plate",
    "wooden_pressure_plate": "Oak Pressure Plate",
    "acacia_pressure_plate": "Acacia Pressure Plate",
    "birch_pressure_plate": "Birch Pressure Plate",
    "dark_oak_pressure_plate": "Dark Oak Pressure Plate",
    "jungle_pressure_plate": "Jungle Pressure Plate",
    "spruce_pressure_plate": "Spruce Pressure Plate",
    "prismarine": [
        "Prismarine Bricks",
        "Dark Prismarine",
        "Prismarine"
    ],
    "pumpkin": "Pumpkin",
    "pumpkin_stem": "Pumpkin Stem",
    "quartz_block": "Block of Quartz",
    "rail": "Rail",
    "red_mushroom": "Red Mushroom",
    "crimson_fungus": "Crimson Fungus",
    "warped_fungus": "Warped Fungus",
    "red_mushroom_block": "Red Mushroom Block",
    "red_sandstone": "Red Sandstone",
    "redstone_wire": "Redstone Dust",
    "redstone_lamp": "Redstone Lamp",
    "reeds": "Sugar cane",
    "sand": "Sand",
    "sandstone": "Sandstone",
    "sapling": [
        "Acacia Sapling",
        "Dark Oak Sapling",
        "Birch Sapling",
        "Jungle Sapling",
        "Oak Sapling",
        "Spruce Sapling"
    ],
    "seaLantern": "Sea Lantern",
    "standing_sign": "Sign",
    "spruce_standing_sign": "Spruce Sign",
    "birch_standing_sign": "Birch Sign",
    "jungle_standing_sign": "Jungle Sign",
    "acacia_standing_sign": "Acacia Sign",
    "darkoak_standing_sign": "Dark Oak Sign",
    "slime": "Slime Block",
    "snow": "Snow",
    "sponge": [
        "Sponge",
        "Wet Sponge"
    ],
    "spruceFence": "Spruce Fence",
    "spruce_fence_gate": "Spruce Fence Gate",
    "brick_stairs": "Brick Stairs",
    "nether_brick_stairs": "Nether Brick Stairs",
    "quartz_stairs": "Quartz Stairs",
    "smooth_quartz_stairs": "Smooth Quartz Stairs",
    "red_sandstone_stairs": "Red Sandstone Stairs",
    "sandstone_stairs": "Sandstone Stairs",
    "stone_stairs": "Cobblestone Stairs",
    "normal_stone_stairs": "Stone Stairs",
    "stone_brick_stairs": "Stone Brick Stairs",
    "oak_stairs": "Oak Wood Stairs",
    "acacia_stairs": "Acacia Wood Stairs",
    "birch_stairs": "Birch Wood Stairs",
    "dark_oak_stairs": "Dark Oak Wood Stairs",
    "jungle_stairs": "Jungle Wood Stairs",
    "spruce_stairs": "Spruce Wood Stairs",
    "purpur_stairs": "Purpur Stairs",
    "prismarine_stairs": "Prismarine Stairs",
    "dark_prismarine_stairs": "Dark Prismarine Stairs",
    "prismarine_bricks_stairs": "Prismarine Brick Stairs",
    "granite_stairs": "Granite Stairs",
    "diorite_stairs": "Diorite Stairs",
    "andesite_stairs": "Andesite Stairs",
    "polished_granite_stairs": "Polished Granite Stairs",
    "polished_diorite_stairs": "Polished Diorite Stairs",
    "polished_andesite_stairs": "Polished Andesite Stairs",
    "mossy_stone_brick_stairs": "Mossy Stone Brick Stairs",
    "smooth_red_sandstone_stairs": "Smooth Red Sandstone Stairs",
    "smooth_sandstone_stairs": "Smooth Sandstone Stairs",
    "end_brick_stairs": "End Stone Brick Stairs",
    "mossy_cobblestone_stairs": "Mossy Cobblestone Stairs",
    "red_nether_brick_stairs": "Red Nether Brick Stairs",
    "smooth_stone": "Smooth Stone",
    "standing_banner": "Banner",
    "stone": [
        "Andesite",
        "Polished Andesite",
        "Diorite",
        "Polished Diorite",
        "Granite",
        "Polished Granite",
        "Stone"
    ],
    "cobblestone": "Cobblestone",
    "stonebrick": "Stone Bricks",
    "stonecutter": "Stonecutter",
    "stonecutter_block": "Stonecutter",
    "mossy_cobblestone": "Mossy Cobblestone",
    "double_stone_slab": "Stone Slab",
    "stone_slab": "Stone Slab",
    "double_stone_slab2": [
        "Red Sandstone Slab"
    ],
    "stone_slab2": [
        "Red Sandstone Slab",
        "Purpur Slab",
        "Prismarine Slab",
        "Dark Prismarine Slab",
        "Prismarine Bricks Slab",
        "Mossy Cobblestone Slab",
        "Red Nether Brick Slab",
        "Smooth Sandstone Slab"
    ],
    "stone_slab3": [
        "End Stone Brick Slab",
        "Smooth Red Sandstone Slab",
        "Polished Andesite Slab",
        "Andesite Slab",
        "Diorite Slab",
        "Polished Diorite Slab",
        "Granite Slab",
        "Polished Granite Slab"
    ],
    "stone_slab4": [
        "Mossy Stone Brick Slab",
        "Smooth Quartz Slab",
        "Stone Slab",
        "Cut Sandstone Slab",
        "Cut Red Sandstone Slab"
    ],
    "coral_block": [
        "Tube Coral Block",
        "Brain Coral Block",
        "Bubble Coral Block",
        "Fire Coral Block",
        "Horn Coral Block",
        "Dead Tube Coral Block",
        "Dead Brain Coral Block",
        "Dead Bubble Coral Block",
        "Dead Fire Coral Block",
        "Dead Horn Coral Block"
    ],
    "tallgrass": "Grass",
    "seagrass": [
        "Seagrass"
    ],
    "sea_pickle": "Sea Pickle",
    "turtle_egg": "Sea Turtle Egg",
    "coral": [
        "Tube Coral",
        "Brain Coral",
        "Bubble Coral",
        "Fire Coral",
        "Horn Coral",
        "Dead Tube Coral",
        "Dead Brain Coral",
        "Dead Bubble Coral",
        "Dead Fire Coral",
        "Dead Horn Coral"
    ],
    "coral_fan": [
        "Tube Coral Fan",
        "Brain Coral Fan",
        "Bubble Coral Fan",
        "Fire Coral Fan",
        "Horn Coral Fan"
    ],
    "coral_fan_dead": [
        "Dead Tube Coral Fan",
        "Dead Brain Coral Fan",
        "Dead Bubble Coral Fan",
        "Dead Fire Coral Fan",
        "Dead Horn Coral Fan"
    ],
    "glass_pane": "Glass Pane",
    "tnt": "TNT",
    "snow_layer": "Top Snow",
    "torch": "Torch",
    "trapdoor": "Oak Trapdoor",
    "acacia_trapdoor": "Acacia Trapdoor",
    "birch_trapdoor": "Birch Trapdoor",
    "dark_oak_trapdoor": "Dark Oak Trapdoor",
    "jungle_trapdoor": "Jungle Trapdoor",
    "spruce_trapdoor": "Spruce Trapdoor",
    "tripWire": "Tripwire",
    "tripwire_hook": "Tripwire Hook",
    "vine": "Vines",
    "weeping_vines": "Weeping Vines",
    "twisting_vines": "Twisting Vines",
    "flowing_water": "Water",
    "water": "Water",
    "waterlily": "Lily Pad",
    "web": "Cobweb",
    "heavy_weighted_pressure_plate": "Weighted Pressure Plate (Heavy)",
    "light_weighted_pressure_plate": "Weighted Pressure Plate (Light)",
    "end_stone": "End Stone",
    "end_bricks": "End Stone Bricks",
    "planks": "Wooden Planks",
    "wooden_slab": "Wood Slab",
    "carpet": "Carpet",
    "crafting_table": [
        "Crafting Tabletile.glazedTerracotta.white.name=White Glazed Terracotta"
    ],
    "glazedTerracotta": [
        "Orange Glazed Terracotta",
        "Magenta Glazed Terracotta",
        "Light Blue Glazed Terracotta",
        "Yellow Glazed Terracotta",
        "Lime Glazed Terracotta",
        "Pink Glazed Terracotta",
        "Gray Glazed Terracotta",
        "Light Gray Glazed Terracotta",
        "Cyan Glazed Terracotta",
        "Purple Glazed Terracotta",
        "Blue Glazed Terracotta",
        "Brown Glazed Terracotta",
        "Green Glazed Terracotta",
        "Red Glazed Terracotta",
        "Black Glazed Terracotta"
    ],
    "concrete": [
        "Black Concrete",
        "Red Concrete",
        "Green Concrete",
        "Brown Concrete",
        "Blue Concrete",
        "Purple Concrete",
        "Cyan Concrete",
        "Light Gray Concrete",
        "Gray Concrete",
        "Pink Concrete",
        "Lime Concrete",
        "Yellow Concrete",
        "Light Blue Concrete",
        "Magenta Concrete",
        "Orange Concrete",
        "White Concrete"
    ],
    "glazedTerracottaWhite": "White Glazed Terracotta",
    "glazedTerracottaOrange": "Orange Glazed Terracotta",
    "glazedTerracottaMagenta": "Magenta Glazed Terracotta",
    "glazedTerracottaLightBlue": "Light Blue Glazed Terracotta",
    "glazedTerracottaYellow": "Yellow Glazed Terracotta",
    "glazedTerracottaLime": "Lime Glazed Terracotta",
    "glazedTerracottaPink": "Pink Glazed Terracotta",
    "glazedTerracottaGray": "Gray Glazed Terracotta",
    "glazedTerracottaSilver": "Light Gray Glazed Terracotta",
    "glazedTerracottaCyan": "Cyan Glazed Terracotta",
    "glazedTerracottaPurple": "Purple Glazed Terracotta",
    "glazedTerracottaBlue": "Blue Glazed Terracotta",
    "glazedTerracottaBrown": "Brown Glazed Terracotta",
    "glazedTerracottaGreen": "Green Glazed Terracotta",
    "glazedTerracottaRed": "Red Glazed Terracotta",
    "glazedTerracottaBlack": "Black Glazed Terracotta",
    "concretePowder": [
        "Black Concrete Powder",
        "Red Concrete Powder",
        "Green Concrete Powder",
        "Brown Concrete Powder",
        "Blue Concrete Powder",
        "Purple Concrete Powder",
        "Cyan Concrete Powder",
        "Light Gray Concrete Powder",
        "Gray Concrete Powder",
        "Pink Concrete Powder",
        "Lime Concrete Powder",
        "Yellow Concrete Powder",
        "Light Blue Concrete Powder",
        "Magenta Concrete Powder",
        "Orange Concrete Powder",
        "White Concrete Powdertile.stripped_spruce_log.name=Stripped Spruce Log"
    ],
    "stripped_dark_oak_log": "Stripped Dark Oak Log",
    "stripped_birch_log": "Stripped Birch Log",
    "stripped_jungle_log": "Stripped Jungle Log",
    "stripped_oak_log": "Stripped Oak Log",
    "stripped_acacia_log": [
        "Stripped Acacia Logtile.bamboo.name=Bamboo"
    ],
    "scaffolding": "Scaffolding",
    "grindstone": "Grindstone",
    "cartography_table": "Cartography Table",
    "lantern": "Lantern",
    "soul_lantern": "Soul Lantern",
    "smoker": "Smoker",
    "smithing_table": "Smithing Table",
    "barrel": "Barrel",
    "campfire": "Campfire",
    "loom": "Loom",
    "lectern": "Lectern",
    "sweet_berry_bush": [
        "Sweet Berry Bushtile.wood.oak.name=Oak Wood"
    ],
    "wood": [
        "Spruce Wood",
        "Birch Wood",
        "Jungle Wood",
        "Acacia Wood",
        "Dark Oak Wood",
        "Stripped Oak Wood",
        "Stripped Spruce Wood",
        "Stripped Birch Wood",
        "Stripped Jungle Wood",
        "Stripped Acacia Wood",
        "Stripped Dark Oak Woodtile.netherite_block.name=Block of Netherite"
    ],
    "ancient_debris": "Ancient Debris",
    "nether_gold_ore": [
        "Nether Gold Oretile.respawn_anchor.name=Respawn Anchor"
    ],
    "crying_obsidian": [
        "Crying Obsidiantile.powder_snow.name=Powder Snow"
    ],
    "deepslate": "Deepslate",
    "infested_deepslate": "Infested Deepslate",
    "cobbled_deepslate": "Cobbled Deepslate",
    "dripstone_block": "Dripstone Block",
    "pointed_dripstone": "Pointed Dripstone",
    "cobbled_deepslate_slab": "Cobbled Deepslate Slab",
    "cobbled_deepslate_stairs": "Cobbled Deepslate Stairs",
    "cobbled_deepslate_wall": "Cobbled Deepslate Wall",
    "polished_deepslate": "Polished Deepslate",
    "polished_deepslate_slab": "Polished Deepslate Slab",
    "polished_deepslate_stairs": "Polished Deepslate Stairs",
    "polished_deepslate_wall": "Polished Deepslate Wall",
    "deepslate_tiles": "Deepslate Tiles",
    "deepslate_tile_slab": "Deepslate Tile Slab",
    "deepslate_tile_stairs": "Deepslate Tile Stairs",
    "deepslate_tile_wall": "Deepslate Tile Wall",
    "deepslate_bricks": "Deepslate Bricks",
    "deepslate_brick_slab": "Deepslate Brick Slab",
    "deepslate_brick_stairs": "Deepslate Brick Stairs",
    "deepslate_brick_wall": "Deepslate Brick Wall",
    "chiseled_deepslate": "Chiseled Deepslate",
    "cobbled_deepslate_double_slab": "Cobbled Deepslate Double Slab",
    "polished_deepslate_double_slab": "Polished Deepslate Double Slab",
    "deepslate_tile_double_slab": "Deepslate Tile Double Slab",
    "deepslate_brick_double_slab": "Deepslate Brick Double Slab",
    "deepslate_lapis_ore": "Deepslate Lapis Lazuli Ore",
    "deepslate_iron_ore": "Deepslate Iron Ore",
    "deepslate_gold_ore": "Deepslate Gold Ore",
    "deepslate_redstone_ore": "Deepslate Redstone Ore",
    "deepslate_diamond_ore": "Deepslate Diamond Ore",
    "deepslate_coal_ore": "Deepslate Coal Ore",
    "deepslate_emerald_ore": "Deepslate Emerald Ore",
    "deepslate_copper_ore": "Deepslate Copper Ore",
    "cracked_deepslate_tiles": "Cracked Deepslate Tiles",
    "cracked_deepslate_bricks": "Cracked Deepslate Bricks",
    "copper_ingot": "Copper Ingot",
    "raw_copper": "Raw Copper",
    "raw_iron": "Raw Iron",
    "raw_gold": "Raw Gold",
    "copper_block": "Block of Copper",
    "exposed_copper": "Exposed Copper",
    "weathered_copper": "Weathered Copper",
    "oxidized_copper": "Oxidized Copper",
    "waxed_copper": "Waxed Block of Copper",
    "waxed_exposed_copper": "Waxed Exposed Copper",
    "waxed_weathered_copper": "Waxed Weathered Copper",
    "waxed_oxidized_copper": [
        "Waxed Oxidized Coppertile.cut_copper.name=Cut Copper"
    ],
    "exposed_cut_copper": "Exposed Cut Copper",
    "weathered_cut_copper": "Weathered Cut Copper",
    "oxidized_cut_copper": "Oxidized Cut Copper",
    "waxed_cut_copper": "Waxed Cut Copper",
    "waxed_exposed_cut_copper": "Waxed Exposed Cut Copper",
    "waxed_weathered_cut_copper": "Waxed Weathered Cut Copper",
    "waxed_oxidized_cut_copper": [
        "Waxed Oxidized Cut Coppertile.cut_copper_stairs.name=Cut Copper Stairs"
    ],
    "exposed_cut_copper_stairs": "Exposed Cut Copper Stairs",
    "weathered_cut_copper_stairs": "Weathered Cut Copper Stairs",
    "oxidized_cut_copper_stairs": "Oxidized Cut Copper Stairs",
    "waxed_cut_copper_stairs": "Waxed Cut Copper Stairs",
    "waxed_exposed_cut_copper_stairs": "Waxed Exposed Cut Copper Stairs",
    "waxed_weathered_cut_copper_stairs": "Waxed Weathered Cut Copper Stairs",
    "waxed_oxidized_cut_copper_stairs": [
        "Waxed Oxidized Cut Copper Stairstile.cut_copper_slab.name=Cut Copper Slab"
    ],
    "exposed_cut_copper_slab": "Exposed Cut Copper Slab",
    "weathered_cut_copper_slab": "Weathered Cut Copper Slab",
    "oxidized_cut_copper_slab": "Oxidized Cut Copper Slab",
    "waxed_cut_copper_slab": "Waxed Cut Copper Slab",
    "waxed_exposed_cut_copper_slab": "Waxed Exposed Cut Copper Slab",
    "waxed_weathered_cut_copper_slab": "Waxed Weathered Cut Copper Slab",
    "waxed_oxidized_cut_copper_slab": "Waxed Oxidized Cut Copper Slab",
    "raw_copper_block": "Block of Raw Copper",
    "raw_iron_block": "Block of Raw Iron",
    "raw_gold_block": "Block of Raw Gold",
    "name": "Copper",
    "tooltip": "Wax Off",
    "white_candle": "White Candle",
    "orange_candle": "Orange Candle",
    "magenta_candle": "Magenta Candle",
    "light_blue_candle": "Light Blue Candle",
    "yellow_candle": "Yellow Candle",
    "lime_candle": "Lime Candle",
    "pink_candle": "Pink Candle",
    "gray_candle": "Gray Candle",
    "light_gray_candle": "Light Gray Candle",
    "cyan_candle": "Cyan Candle",
    "purple_candle": "Purple Candle",
    "blue_candle": "Blue Candle",
    "brown_candle": "Brown Candle",
    "green_candle": "Green Candle",
    "red_candle": "Red Candle",
    "black_candle": "Black Candle",
    "candle_cake": "Cake with Candle",
    "white_candle_cake": "Cake with White Candle",
    "orange_candle_cake": "Cake with Orange Candle",
    "magenta_candle_cake": "Cake with Magenta Candle",
    "light_blue_candle_cake": "Cake with Light Blue Candle",
    "yellow_candle_cake": "Cake with Yellow Candle",
    "lime_candle_cake": "Cake with Lime Candle",
    "pink_candle_cake": "Cake with Pink Candle",
    "gray_candle_cake": "Cake with Gray Candle",
    "light_gray_candle_cake": "Cake with Light Gray Candle",
    "cyan_candle_cake": "Cake with Cyan Candle",
    "purple_candle_cake": "Cake with Purple Candle",
    "blue_candle_cake": "Cake with Blue Candle",
    "brown_candle_cake": "Cake with Brown Candle",
    "green_candle_cake": "Cake with Green Candle",
    "red_candle_cake": "Cake with Red Candle",
    "black_candle_cake": [
        "Cake with Black Candleitem.spyglass.name=Spyglass"
    ],
    "amethyst_shard": "Amethyst Shard",
    "amethyst_block": "Amethyst Block",
    "budding_amethyst": "Budding Amethyst",
    "amethyst_cluster": "Amethyst Cluster",
    "large_amethyst_bud": "Large Amethyst Bud",
    "medium_amethyst_bud": "Medium Amethyst Bud",
    "small_amethyst_bud": "Small Amethyst Bud",
    "tuff": "Tuff",
    "calcite": "Calcite",
    "tinted_glass": "Tinted Glass",
    "smooth_basalt": "Smooth Basalt"
};
//# sourceMappingURL=tile_name_object.js.map