const texturePathObject = {
    "acacia_door": "textures/items/door_acacia",
    "apple": "textures/items/apple",
    "apple_golden": "textures/items/apple_golden",
    "armor_stand": "textures/items/armor_stand",
    "wood_axe": "textures/items/wood_axe",
    "stone_axe": "textures/items/stone_axe",
    "iron_axe": "textures/items/iron_axe",
    "gold_axe": "textures/items/gold_axe",
    "diamond_axe": "textures/items/diamond_axe",
    "netherite_axe": "textures/items/netherite_axe",
    "banner_pattern": "textures/items/banner_pattern",
    "white_bed": "textures/items/bed_white",
    "orange_bed": "textures/items/bed_orange",
    "magenta_bed": "textures/items/bed_magenta",
    "light_blue_bed": "textures/items/bed_light_blue",
    "yellow_bed": "textures/items/bed_yellow",
    "lime_bed": "textures/items/bed_lime",
    "pink_bed": "textures/items/bed_pink",
    "gray_bed": "textures/items/bed_gray",
    "silver_bed": "textures/items/bed_silver",
    "cyan_bed": "textures/items/bed_cyan",
    "purple_bed": "textures/items/bed_purple",
    "blue_bed": "textures/items/bed_blue",
    "brown_bed": "textures/items/bed_brown",
    "green_bed": "textures/items/bed_green",
    "red_bed": "textures/items/bed_red",
    "black_bed": "textures/items/bed_black",
    "beef_cooked": "textures/items/beef_cooked",
    "beef_raw": "textures/items/beef_raw",
    "beetroot": "textures/items/beetroot",
    "beetroot_soup": "textures/items/beetroot_soup",
    "birch_door": "textures/items/door_birch",
    "blaze_powder": "textures/items/blaze_powder",
    "blaze_rod": "textures/items/blaze_rod",
    "boat": [
        "textures/items/boat_oak",
        "textures/items/boat_spruce",
        "textures/items/boat_birch",
        "textures/items/boat_jungle",
        "textures/items/boat_acacia",
        "textures/items/boat_darkoak"
    ],
    "bone": "textures/items/bone",
    "book_enchanted": "textures/items/book_enchanted",
    "book_normal": "textures/items/book_normal",
    "book_portfolio": "textures/items/book_portfolio",
    "book_writable": "textures/items/book_writable",
    "book_written": "textures/items/book_written",
    "leather_boots": "textures/items/leather_boots",
    "chainmail_boots": "textures/items/chainmail_boots",
    "iron_boots": "textures/items/iron_boots",
    "gold_boots": "textures/items/gold_boots",
    "diamond_boots": "textures/items/diamond_boots",
    "netherite_boots": "textures/items/netherite_boots",
    "bow_pulling": [
        "textures/items/bow_pulling_0",
        "textures/items/bow_pulling_1",
        "textures/items/bow_pulling_2"
    ],
    "bow_standby": "textures/items/bow_standby",
    "bowl": "textures/items/bowl",
    "bread": "textures/items/bread",
    "brewing_stand": "textures/items/brewing_stand",
    "brick": "textures/items/brick",
    "bucket": [
        "textures/items/bucket_empty",
        "textures/items/bucket_milk",
        "textures/items/bucket_water",
        "textures/items/bucket_lava",
        "textures/items/bucket_cod",
        "textures/items/bucket_salmon",
        "textures/items/bucket_tropical",
        "textures/items/bucket_pufferfish"
    ],
    "cake": "textures/items/cake",
    "camera": "textures/items/camera",
    "campfire": "textures/items/campfire",
    "carrot": "textures/items/carrot",
    "carrot_golden": "textures/items/carrot_golden",
    "carrot_on_a_stick": "textures/items/carrot_on_a_stick",
    "cauldron": "textures/items/cauldron",
    "chain": "textures/items/chain",
    "chalkboard": [
        "textures/items/chalkboard_small",
        "textures/items/chalkboard_medium",
        "textures/items/chalkboard_large"
    ],
    "charcoal": "textures/items/charcoal",
    "leather_chestplate": "textures/items/leather_chestplate",
    "chainmail_chestplate": "textures/items/chainmail_chestplate",
    "iron_chestplate": "textures/items/iron_chestplate",
    "gold_chestplate": "textures/items/gold_chestplate",
    "diamond_chestplate": "textures/items/diamond_chestplate",
    "netherite_chestplate": "textures/items/netherite_chestplate",
    "chicken_cooked": "textures/items/chicken_cooked",
    "chicken_raw": "textures/items/chicken_raw",
    "chorus_fruit": "textures/items/chorus_fruit",
    "chorus_fruit_popped": "textures/items/chorus_fruit_popped",
    "clay_ball": "textures/items/clay_ball",
    "clock": "textures/items/clock_item",
    "clownfish": "textures/items/fish_clownfish_raw",
    "coal": "textures/items/coal",
    "comparator": "textures/items/comparator",
    "compass": "textures/items/compass_item",
    "cooked_fish": "textures/items/fish_cooked",
    "cooked_salmon": "textures/items/fish_salmon_cooked",
    "cookie": "textures/items/cookie",
    "crimson_door": "textures/items/crimson_door",
    "crimson_sign": "textures/items/sign_crimson",
    "crossbow_pulling": [
        "textures/items/crossbow_pulling_0",
        "textures/items/crossbow_pulling_1",
        "textures/items/crossbow_pulling_2",
        "textures/items/crossbow_arrow",
        "textures/items/crossbow_firework"
    ],
    "crossbow_standby": "textures/items/crossbow_standby",
    "dark_oak_door": "textures/items/door_dark_oak",
    "diamond": "textures/items/diamond",
    "diamond_horse_armor": "textures/items/diamond_horse_armor",
    "dragon_breath": "textures/items/dragons_breath",
    "dried_kelp": "textures/items/dried_kelp",
    "black_dye": "textures/items/dye_powder_black",
    "red_dye": "textures/items/dye_powder_red",
    "green_dye": "textures/items/dye_powder_green",
    "brown_dye": "textures/items/dye_powder_brown",
    "blue_dye": "textures/items/dye_powder_blue",
    "purple_dye": "textures/items/dye_powder_purple",
    "cyan_dye": "textures/items/dye_powder_cyan",
    "silver_dye": "textures/items/dye_powder_silver",
    "gray_dye": "textures/items/dye_powder_gray",
    "pink_dye": "textures/items/dye_powder_pink",
    "lime_dye": "textures/items/dye_powder_lime",
    "yellow_dye": "textures/items/dye_powder_yellow",
    "light_blue_dye": "textures/items/dye_powder_light_blue",
    "magenta_dye": "textures/items/dye_powder_magenta",
    "orange_dye": "textures/items/dye_powder_orange",
    "white_dye": "textures/items/dye_powder_white",
    "black_new_dye": "textures/items/dye_powder_black_new",
    "brown_new_dye": "textures/items/dye_powder_brown_new",
    "blue_new_dye": "textures/items/dye_powder_blue_new",
    "white_new_dye": "textures/items/dye_powder_white_new",
    "egg": "textures/items/egg",
    "egg_bee": [
        "textures/items/egg_bee"
    ],
    "elytra": [
        "textures/items/elytra",
        "textures/items/broken_elytra"
    ],
    "emerald": "textures/items/emerald",
    "empty_armor_slot_boots": "textures/items/empty_armor_slot_boots",
    "empty_armor_slot_chestplate": "textures/items/empty_armor_slot_chestplate",
    "empty_armor_slot_helmet": "textures/items/empty_armor_slot_helmet",
    "empty_armor_slot_leggings": "textures/items/empty_armor_slot_leggings",
    "empty_armor_slot_shield": "textures/items/empty_armor_slot_shield",
    "end_crystal": "textures/items/end_crystal",
    "ender_eye": "textures/items/ender_eye",
    "ender_pearl": "textures/items/ender_pearl",
    "experience_bottle": "textures/items/experience_bottle",
    "feather": "textures/items/feather",
    "fireball": "textures/items/fireball",
    "fireworks": "textures/items/fireworks",
    "fireworks_charge": [
        "textures/items/fireworks_charge"
    ],
    "fish": "textures/items/fish_raw",
    "fishing_rod": [
        "textures/items/fishing_rod_uncast",
        "textures/items/fishing_rod_cast"
    ],
    "flint": "textures/items/flint",
    "flint_and_steel": "textures/items/flint_and_steel",
    "flower_pot": "textures/items/flower_pot",
    "ghast_tear": "textures/items/ghast_tear",
    "glowstone_dust": "textures/items/glowstone_dust",
    "gold_horse_armor": "textures/items/gold_horse_armor",
    "gold_ingot": "textures/items/gold_ingot",
    "gold_nugget": "textures/items/gold_nugget",
    "gunpowder": "textures/items/gunpowder",
    "heart_of_the_sea": "textures/items/heartofthesea_closed",
    "leather_helmet": "textures/items/leather_helmet",
    "chainmail_helmet": "textures/items/chainmail_helmet",
    "iron_helmet": "textures/items/iron_helmet",
    "gold_helmet": "textures/items/gold_helmet",
    "diamond_helmet": "textures/items/diamond_helmet",
    "netherite_helmet": "textures/items/netherite_helmet",
    "wood_hoe": "textures/items/wood_hoe",
    "stone_hoe": "textures/items/stone_hoe",
    "iron_hoe": "textures/items/iron_hoe",
    "gold_hoe": "textures/items/gold_hoe",
    "diamond_hoe": "textures/items/diamond_hoe",
    "netherite_hoe": "textures/items/netherite_hoe",
    "honey_bottle": "textures/items/honey_bottle",
    "honeycomb": "textures/items/honeycomb",
    "hopper": "textures/items/hopper",
    "iron_door": "textures/items/door_iron",
    "iron_horse_armor": "textures/items/iron_horse_armor",
    "iron_ingot": "textures/items/iron_ingot",
    "iron_nugget": "textures/items/iron_nugget",
    "item_frame": "textures/items/item_frame",
    "jungle_door": "textures/items/door_jungle",
    "kelp": "textures/items/kelp",
    "lead": "textures/items/lead",
    "leather": "textures/items/leather",
    "leather_horse_armor": "textures/items/leather_horse_armor",
    "leather_leggings": "textures/items/leather_leggings",
    "chainmail_leggings": "textures/items/chainmail_leggings",
    "iron_leggings": "textures/items/iron_leggings",
    "gold_leggings": "textures/items/gold_leggings",
    "diamond_leggings": "textures/items/diamond_leggings",
    "netherite_leggings": "textures/items/netherite_leggings",
    "lever": "textures/items/lever",
    "lodestonecompass": "textures/items/lodestonecompass_item",
    "magma_cream": "textures/items/magma_cream",
    "map_empty": "textures/items/map_empty",
    "map_filled": [
        "textures/items/map_filled",
        "textures/items/map_filled",
        "textures/items/map_filled",
        "textures/items/map_monument",
        "textures/items/map_mansion",
        "textures/items/map_nautilus",
        "textures/items/map_locked"
    ],
    "melon": "textures/items/melon",
    "melon_speckled": "textures/items/melon_speckled",
    "minecart_chest": "textures/items/minecart_chest",
    "minecart_command_block": "textures/items/minecart_command_block",
    "minecart_furnace": "textures/items/minecart_furnace",
    "minecart_hopper": "textures/items/minecart_hopper",
    "minecart_normal": "textures/items/minecart_normal",
    "minecart_tnt": "textures/items/minecart_tnt",
    "mushroom_stew": "textures/items/mushroom_stew",
    "mutton_cooked": "textures/items/mutton_cooked",
    "mutton_raw": "textures/items/mutton_raw",
    "name_tag": "textures/items/name_tag",
    "nautilus_shell": "textures/items/nautilus",
    "nether_sprouts": "textures/items/nether_sprouts",
    "nether_star": "textures/items/nether_star",
    "nether_wart": "textures/items/nether_wart",
    "netherbrick": "textures/items/netherbrick",
    "netherite_ingot": "textures/items/netherite_ingot",
    "netherite_scrap": "textures/items/netherite_scrap",
    "painting": "textures/items/painting",
    "paper": "textures/items/paper",
    "phantom_membrane": "textures/items/phantom_membrane",
    "wood_pickaxe": "textures/items/wood_pickaxe",
    "stone_pickaxe": "textures/items/stone_pickaxe",
    "iron_pickaxe": "textures/items/iron_pickaxe",
    "gold_pickaxe": "textures/items/gold_pickaxe",
    "diamond_pickaxe": "textures/items/diamond_pickaxe",
    "netherite_pickaxe": "textures/items/netherite_pickaxe",
    "porkchop_cooked": "textures/items/porkchop_cooked",
    "porkchop_raw": "textures/items/porkchop_raw",
    "potato": "textures/items/potato",
    "potato_baked": "textures/items/potato_baked",
    "potato_poisonous": "textures/items/potato_poisonous",
    "potion": [
        "textures/items/potion_bottle_drinkable",
        "textures/items/potion_bottle_moveSpeed",
        "textures/items/potion_bottle_moveSlowdown",
        "textures/items/potion_bottle_digSpeed",
        "textures/items/potion_bottle_digSlowdown",
        "textures/items/potion_bottle_damageBoost",
        "textures/items/potion_bottle_heal",
        "textures/items/potion_bottle_harm",
        "textures/items/potion_bottle_jump",
        "textures/items/potion_bottle_confusion",
        "textures/items/potion_bottle_regeneration",
        "textures/items/potion_bottle_resistance",
        "textures/items/potion_bottle_fireResistance",
        "textures/items/potion_bottle_waterBreathing",
        "textures/items/potion_bottle_invisibility",
        "textures/items/potion_bottle_blindness",
        "textures/items/potion_bottle_nightVision",
        "textures/items/potion_bottle_hunger",
        "textures/items/potion_bottle_weakness",
        "textures/items/potion_bottle_poison",
        "textures/items/potion_bottle_wither",
        "textures/items/potion_bottle_healthBoost",
        "textures/items/potion_bottle_absorption",
        "textures/items/potion_bottle_saturation",
        "textures/items/potion_bottle_levitation",
        "textures/items/potion_bottle_turtleMaster",
        "textures/items/potion_bottle_slowFall"
    ],
    "empty_bottle": "textures/items/potion_bottle_empty",
    "lingering_potion": [
        "textures/items/potion_bottle_lingering",
        "textures/items/potion_bottle_lingering_moveSpeed",
        "textures/items/potion_bottle_lingering_moveSlowdown",
        "textures/items/potion_bottle_lingering_damageBoost",
        "textures/items/potion_bottle_lingering_heal",
        "textures/items/potion_bottle_lingering_harm",
        "textures/items/potion_bottle_lingering_jump",
        "textures/items/potion_bottle_lingering_regeneration",
        "textures/items/potion_bottle_lingering_fireResistance",
        "textures/items/potion_bottle_lingering_waterBreathing",
        "textures/items/potion_bottle_lingering_invisibility",
        "textures/items/potion_bottle_lingering_nightVision",
        "textures/items/potion_bottle_lingering_weakness",
        "textures/items/potion_bottle_lingering_poison",
        "textures/items/potion_bottle_lingering_wither",
        "textures/items/potion_bottle_lingering_turtleMaster",
        "textures/items/potion_bottle_lingering_slowFall"
    ],
    "splash_potion": [
        "textures/items/potion_bottle_splash",
        "textures/items/potion_bottle_splash_moveSpeed",
        "textures/items/potion_bottle_splash_moveSlowdown",
        "textures/items/potion_bottle_splash_digSpeed",
        "textures/items/potion_bottle_splash_digSlowdown",
        "textures/items/potion_bottle_splash_damageBoost",
        "textures/items/potion_bottle_splash_heal",
        "textures/items/potion_bottle_splash_harm",
        "textures/items/potion_bottle_splash_jump",
        "textures/items/potion_bottle_splash_confusion",
        "textures/items/potion_bottle_splash_regeneration",
        "textures/items/potion_bottle_splash_resistance",
        "textures/items/potion_bottle_splash_fireResistance",
        "textures/items/potion_bottle_splash_waterBreathing",
        "textures/items/potion_bottle_splash_invisibility",
        "textures/items/potion_bottle_splash_blindness",
        "textures/items/potion_bottle_splash_nightVision",
        "textures/items/potion_bottle_splash_hunger",
        "textures/items/potion_bottle_splash_weakness",
        "textures/items/potion_bottle_splash_poison",
        "textures/items/potion_bottle_splash_wither",
        "textures/items/potion_bottle_splash_healthBoost",
        "textures/items/potion_bottle_splash_absorption",
        "textures/items/potion_bottle_splash_saturation",
        "textures/items/potion_bottle_splash_turtleMaster",
        "textures/items/potion_bottle_splash_slowFall"
    ],
    "potion_overlay": "textures/items/potion_overlay",
    "prismarine_crystals": "textures/items/prismarine_crystals",
    "prismarine_shard": "textures/items/prismarine_shard",
    "pufferfish": "textures/items/fish_pufferfish_raw",
    "pumpkin_pie": "textures/items/pumpkin_pie",
    "quartz": "textures/items/quartz",
    "quiver": "textures/items/quiver",
    "rabbit": "textures/items/rabbit_raw",
    "rabbit_cooked": "textures/items/rabbit_cooked",
    "rabbit_foot": "textures/items/rabbit_foot",
    "rabbit_hide": "textures/items/rabbit_hide",
    "rabbit_stew": "textures/items/rabbit_stew",
    "record_11": "textures/items/record_11",
    "record_13": "textures/items/record_13",
    "record_blocks": "textures/items/record_blocks",
    "record_cat": "textures/items/record_cat",
    "record_chirp": "textures/items/record_chirp",
    "record_far": "textures/items/record_far",
    "record_mall": "textures/items/record_mall",
    "record_mellohi": "textures/items/record_mellohi",
    "record_pigstep": "textures/items/record_pigstep",
    "record_stal": "textures/items/record_stal",
    "record_strad": "textures/items/record_strad",
    "record_wait": "textures/items/record_wait",
    "record_ward": "textures/items/record_ward",
    "redstone_dust": "textures/items/redstone_dust",
    "reeds": "textures/items/reeds",
    "repeater": "textures/items/repeater",
    "rotten_flesh": "textures/items/rotten_flesh",
    "saddle": "textures/items/saddle",
    "salmon": "textures/items/fish_salmon_raw",
    "seeds_beetroot": "textures/items/seeds_beetroot",
    "seeds_melon": "textures/items/seeds_melon",
    "seeds_pumpkin": "textures/items/seeds_pumpkin",
    "seeds_wheat": "textures/items/seeds_wheat",
    "shears": "textures/items/shears",
    "shield": "textures/entity/shield",
    "wood_shovel": "textures/items/wood_shovel",
    "stone_shovel": "textures/items/stone_shovel",
    "iron_shovel": "textures/items/iron_shovel",
    "gold_shovel": "textures/items/gold_shovel",
    "diamond_shovel": "textures/items/diamond_shovel",
    "netherite_shovel": "textures/items/netherite_shovel",
    "shulker_shell": "textures/items/shulker_shell",
    "sign": "textures/items/sign",
    "sign_acacia": "textures/items/sign_acacia",
    "sign_birch": "textures/items/sign_birch",
    "sign_darkoak": "textures/items/sign_darkoak",
    "sign_jungle": "textures/items/sign_jungle",
    "sign_spruce": "textures/items/sign_spruce",
    "slimeball": "textures/items/slimeball",
    "snowball": "textures/items/snowball",
    "soul_campfire": "textures/items/soul_campfire",
    "spawn_egg": [
        "textures/items/egg_chicken",
        "textures/items/egg_cow",
        "textures/items/egg_pig",
        "textures/items/egg_sheep",
        "textures/items/egg_wolf",
        "textures/items/egg_mushroomcow",
        "textures/items/egg_creeper",
        "textures/items/egg_enderman",
        "textures/items/egg_silverfish",
        "textures/items/egg_skeleton",
        "textures/items/egg_slime",
        "textures/items/egg_spider",
        "textures/items/egg_zombie",
        "textures/items/egg_pigzombie",
        "textures/items/egg_villager",
        "textures/items/egg_squid",
        "textures/items/egg_ocelot",
        "textures/items/egg_witch",
        "textures/items/egg_bat",
        "textures/items/egg_ghast",
        "textures/items/egg_lava_slime",
        "textures/items/egg_blaze",
        "textures/items/egg_cave_spider",
        "textures/items/egg_horse",
        "textures/items/egg_rabbit",
        "textures/items/egg_endermite",
        "textures/items/egg_guardian",
        "textures/items/egg_stray",
        "textures/items/egg_husk",
        "textures/items/egg_wither",
        "textures/items/egg_donkey",
        "textures/items/egg_mule",
        "textures/items/egg_skeletonhorse",
        "textures/items/egg_zombiehorse",
        "textures/items/egg_shulker",
        "textures/items/egg_npc",
        "textures/items/egg_elderguardian",
        "textures/items/egg_polarbear",
        "textures/items/egg_llama",
        "textures/items/egg_vindicator",
        "textures/items/egg_evoker",
        "textures/items/egg_vex",
        "textures/items/egg_zombievillager",
        "textures/items/egg_parrot",
        "textures/items/egg_clownfish",
        "textures/items/egg_cod",
        "textures/items/egg_pufferfish",
        "textures/items/egg_salmon",
        "textures/items/egg_drowned",
        "textures/items/egg_dolphin",
        "textures/items/egg_turtle",
        "textures/items/egg_phantom",
        "textures/items/egg_agent",
        "textures/items/egg_cat",
        "textures/items/egg_panda",
        "textures/items/egg_fox",
        "textures/items/egg_pillager",
        "textures/items/egg_ravager",
        "textures/items/egg_null",
        "textures/items/egg_mask"
    ],
    "chicken_spawn_egg": "textures/items/egg_chicken",
    "cow_spawn_egg": "textures/items/egg_cow",
    "pig_spawn_egg": "textures/items/egg_pig",
    "sheep_spawn_egg": "textures/items/egg_sheep",
    "wolf_spawn_egg": "textures/items/egg_wolf",
    "mushroomcow_spawn_egg": "textures/items/egg_mushroomcow",
    "creeper_spawn_egg": "textures/items/egg_creeper",
    "enderman_spawn_egg": "textures/items/egg_enderman",
    "silverfish_spawn_egg": "textures/items/egg_silverfish",
    "skeleton_spawn_egg": "textures/items/egg_skeleton",
    "slime_spawn_egg": "textures/items/egg_slime",
    "spider_spawn_egg": "textures/items/egg_spider",
    "zombie_spawn_egg": "textures/items/egg_zombie",
    "pigzombie_spawn_egg": "textures/items/egg_pigzombie",
    "villager_spawn_egg": "textures/items/egg_villager",
    "squid_spawn_egg": "textures/items/egg_squid",
    "ocelot_spawn_egg": "textures/items/egg_ocelot",
    "witch_spawn_egg": "textures/items/egg_witch",
    "bat_spawn_egg": "textures/items/egg_bat",
    "ghast_spawn_egg": "textures/items/egg_ghast",
    "lava_slime_spawn_egg": "textures/items/egg_lava_slime",
    "blaze_spawn_egg": "textures/items/egg_blaze",
    "cave_spider_spawn_egg": "textures/items/egg_cave_spider",
    "horse_spawn_egg": "textures/items/egg_horse",
    "rabbit_spawn_egg": "textures/items/egg_rabbit",
    "endermite_spawn_egg": "textures/items/egg_endermite",
    "guardian_spawn_egg": "textures/items/egg_guardian",
    "stray_spawn_egg": "textures/items/egg_stray",
    "husk_spawn_egg": "textures/items/egg_husk",
    "wither_spawn_egg": "textures/items/egg_wither",
    "donkey_spawn_egg": "textures/items/egg_donkey",
    "mule_spawn_egg": "textures/items/egg_mule",
    "skeleton_horse_spawn_egg": "textures/items/egg_skeletonhorse",
    "zombie_horse_spawn_egg": "textures/items/egg_zombiehorse",
    "shulker_spawn_egg": "textures/items/egg_shulker",
    "npc_spawn_egg": "textures/items/egg_npc",
    "elder_guardian_spawn_egg": "textures/items/egg_elderguardian",
    "polarbear_spawn_egg": "textures/items/egg_polarbear",
    "llama_spawn_egg": "textures/items/egg_llama",
    "vindicator_spawn_egg": "textures/items/egg_vindicator",
    "evoker_spawn_egg": "textures/items/egg_evoker",
    "vex_spawn_egg": "textures/items/egg_vex",
    "zombievillager_spawn_egg": "textures/items/egg_zombievillager",
    "parrot_spawn_egg": "textures/items/egg_parrot",
    "clownfish_spawn_egg": "textures/items/egg_clownfish",
    "cod_spawn_egg": "textures/items/egg_cod",
    "pufferfish_spawn_egg": "textures/items/egg_pufferfish",
    "salmon_spawn_egg": "textures/items/egg_salmon",
    "drowned_spawn_egg": "textures/items/egg_drowned",
    "dolphin_spawn_egg": "textures/items/egg_dolphin",
    "turtle_spawn_egg": "textures/items/egg_turtle",
    "phantom_spawn_egg": "textures/items/egg_phantom",
    "agent_spawn_egg": "textures/items/egg_agent",
    "cat_spawn_egg": "textures/items/egg_cat",
    "panda_spawn_egg": "textures/items/egg_panda",
    "fox_spawn_egg": "textures/items/egg_fox",
    "pillager_spawn_egg": "textures/items/egg_pillager",
    "ravager_spawn_egg": "textures/items/egg_ravager",
    "null_spawn_egg": "textures/items/egg_null",
    "mask_spawn_egg": "textures/items/egg_mask",
    "wandering_trader_spawn_egg": "textures/items/egg_wanderingtrader",
    "spider_eye": "textures/items/spider_eye",
    "spider_eye_fermented": "textures/items/spider_eye_fermented",
    "spruce_door": "textures/items/door_spruce",
    "stick": "textures/items/stick",
    "string": "textures/items/string",
    "sugar": "textures/items/sugar",
    "suspicious_stew": "textures/items/suspicious_stew",
    "sweet_berries": "textures/items/sweet_berries",
    "wood_sword": "textures/items/wood_sword",
    "stone_sword": "textures/items/stone_sword",
    "iron_sword": "textures/items/iron_sword",
    "gold_sword": "textures/items/gold_sword",
    "diamond_sword": "textures/items/diamond_sword",
    "netherite_sword": "textures/items/netherite_sword",
    "arrow": [
        "textures/items/arrow",
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        "textures/items/tipped_arrow",
        "textures/items/tipped_arrow_swift",
        "textures/items/tipped_arrow_slow",
        "textures/items/tipped_arrow_strength",
        "textures/items/tipped_arrow_healing",
        "textures/items/tipped_arrow_harm",
        "textures/items/tipped_arrow_leaping",
        "textures/items/tipped_arrow_regen",
        "textures/items/tipped_arrow_fireres",
        "textures/items/tipped_arrow_waterbreathing",
        "textures/items/tipped_arrow_invisibility",
        "textures/items/tipped_arrow_nightvision",
        "textures/items/tipped_arrow_weakness",
        "textures/items/tipped_arrow_poison",
        "textures/items/tipped_arrow_wither",
        "textures/items/tipped_arrow_turtlemaster",
        "textures/items/tipped_arrow_slowfalling"
    ],
    "totem": "textures/items/totem",
    "trident": "textures/items/trident",
    "turtle_helmet": "textures/items/turtle_helmet",
    "turtle_shell_piece": "textures/items/turtle_shell_piece",
    "warped_door": "textures/items/warped_door",
    "warped_fungus_on_a_stick": "textures/items/warped_fungus_on_a_stick",
    "warped_sign": "textures/items/sign_warped",
    "wheat": "textures/items/wheat",
    "wooden_door": "textures/items/door_wood"
};
export const texturePaths = new Proxy({}, {
    get(target, id, value) {
        id = id.replace('minecraft:', '');
        const texture = texturePathObject[id];
        if (!texture)
            return;
        return texture;
    }
});
//# sourceMappingURL=texture_path.js.map